version = 1

[[annotations]]
path = "xdg-shell.xml"
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright 2008-2013 Kristian Høgsberg",
                          "Copyright 2013      Rafael Antognolli",
                          "Copyright 2013      Jasper St. Pierre",
                          "Copyright 2010-2013 Intel Corporation",
                          "Copyright 2015-2017 Samsung Electronics Co., Ltd",
                          "Copyright 2015-2017 Red Hat Inc."]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "xdg-shell-unstable-v6.xml"
precedence = "closest"
comment = "missing from qt_atttribution.json"
SPDX-FileCopyrightText = ["Copyright © 2008-2013 Kristian Høgsberg",
                          "Copyright © 2013      Rafael Antognolli",
                          "Copyright © 2013      Jasper St. Pierre",
                          "Copyright © 2010-2013 Intel Corporation"]
SPDX-License-Identifier = "MIT"
