version = 1

[[annotations]]
path = ["TitilliumWeb-Regular.ttf", "TitilliumWeb-SemiBold.ttf"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2009-2011 by Accademia di Belle Arti di Urbino and students of MA course of Visual design. Some rights reserved."
SPDX-License-Identifier = "OFL-1.1"
