version = 1

[[annotations]]
path = ["include/**", "pxshared/**", "source/**"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2021 NVIDIA Corporation"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["*.patch"]
precedence = "override"
comment = "Licensed as the code itself"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["*.py"]
precedence = "closest"
comment = "tool"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0"


