version = 1

[[annotations]]
path = ["Base64.java", "Base64DecoderException.java", "Security.java"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (C) 2015 The Qt Company Ltd.",
                          "Copyright (c) 2012 Google Inc."]
SPDX-License-Identifier = "Apache-2.0"
