version = 1

[[annotations]]
path = ["imagine.sketch"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"

[[annotations]]
path = ["9-patch-export.sketchplugin/Contents/Sketch/*"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2016 Jesús Espino and Xavier Julian"
SPDX-License-Identifier = "MIT"
