version = 1

[[annotations]]
path = "text-input-unstable-v3.xml"
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright 2012, 2013 Intel Corporation",
                          "Copyright 2015, 2016 Jan Arne Petersen",
                          "Copyright 2017, 2018 Red Hat, Inc.",
                          "Copyright 2018       Purism SPC"]
SPDX-License-Identifier = "MIT"
