version = 1

[[annotations]]
path = ["**.vert", "quickcontrols/designer/qtquickcontrols2.metainfo",
        "quick/scenegraph/shaders_ng/shapestroke.frag"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
