version = 1

[[annotations]]
path = "text-input-unstable-v2.xml"
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright © 2012, 2013 Intel Corporation",
                          "Copyright © 2015, 2016 Jan Arne Petersen"]
SPDX-License-Identifier = "HPND"
