version = 1

[[annotations]]
path = ["org.freedesktop.dbus.objectmanager.xml",
        "org.freedesktop.dbus.properties.xml",
        "org.neard.Adapter.xml",
        "org.neard.Tag.xml"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
