version = 1

[[annotations]]
path = "wayland.xml"
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright © 2008-2011 Kristian Høgsberg",
                          "Copyright © 2010-2011 Intel Corporation",
                          "Copyright © 2012-2013 Collabora, Ltd."]
SPDX-License-Identifier = "MIT"
